apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: thinklabs-blog
  labels:
    app: thinklabs-blog
  name: thinklabs-blog
spec:
  selector:
    matchLabels:
      app: thinklabs-blog
  template:
    metadata:
      labels:
        app: thinklabs-blog
    spec:
      containers:
        - image: 859856990833.dkr.ecr.us-east-2.amazonaws.com/thinklabs-blog-wordpress:04326
          name: thinklabs-blog
          env:
            - name: WORDPRESS_DB_HOST
              value: thinklabs-db.c9y241ptyj2k.us-east-2.rds.amazonaws.com
            - name: WORDPRESS_DB_USER
              value: 'thinklabs'
            - name: WORDPRESS_DB_PASSWORD
              value: 'USIONVURLbAc'
            - name: WORDPRESS_DB_NAME
              value: 'thinklabs_blog'

          ports:
          - containerPort: 80
            name: wordpress
          resources:
            requests:
              memory: 512Mi
              cpu: 500m
            limits:
              memory: 512Mi
              cpu: 500m
      restartPolicy: Always