apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: thinklabs-wp-site
  name: thinklabs-wp-site-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/server-snippet: |
      more_set_headers "X-Forwarded-Proto: https";
      more_set_headers "use-forwarded-headers: true";
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - wp-dev.thinklabs.io
      secretName: thinklab-io-tls
  rules:
    - host: wp-dev.thinklabs.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: thinklabs-wp-site-svc
                port:
                  number: 80
                  